// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDate: typeof import('./src/components/core/AppDate.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
    ThreadListItem: typeof import('./src/components/ThreadListItem.vue')['default']
  }
}
