// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDate: typeof import('./src/components/core/AppDate.vue')['default']
    AppLoadingIndicator: typeof import('./src/components/core/AppLoadingIndicator.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    CategoryListItem: typeof import('./src/components/CategoryListItem.vue')['default']
    ForumList: typeof import('./src/components/ForumList.vue')['default']
    ForumListItem: typeof import('./src/components/ForumListItem.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    ThreadEditor: typeof import('./src/components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
    ThreadListItem: typeof import('./src/components/ThreadListItem.vue')['default']
    UserProfileCard: typeof import('./src/components/user/UserProfileCard.vue')['default']
    UserProfileCardEditor: typeof import('./src/components/user/UserProfileCardEditor.vue')['default']
  }
}
